# in agents/verdict_agent.py

from langchain_core.messages import HumanMessage, AIMessage
from .base import safe_get_content

class VerdictAgent:
    def __init__(self, llms):
        self.llms = llms

    def render_verdict(self, debate_transcript: str):
        # This is the specialized prompt for the final verdict.
        prompt = f"""
        You are the Presiding Judge, and your sole duty is to deliver the final, binding verdict in the case of State vs. Rohan Malhotra.
        You have been provided with the complete transcript of the courtroom proceedings, including all arguments from the prosecution and the defense, and all your own interim evaluations.

        **Your Task:**
        Your only responsibility is to analyze the entire debate and render a definitive verdict. Your decision must be based on which side was more persuasive according to these criteria:
        1.  **Strength of Legal Arguments:** Which side used legal principles and case law more effectively?
        2.  **Quality of Evidence:** Which side's evidence (or critique of evidence) was more convincing? (e.g., forensic logs, expert testimony).
        3.  **Burden of Proof:** Did the prosecution successfully prove guilt "beyond a reasonable doubt"? Or did the defense successfully create "reasonable doubt"?

        **Output Format:**
        You MUST begin your response with the line "VERDICT DELIVERED:" and structure your entire response in the following format:

        VERDICT DELIVERED: [GUILTY / NOT GUILTY]

        REASONING:
        [Provide a detailed, step-by-step explanation for your decision. Reference specific arguments and turning points from the transcript that led to your conclusion. Explain which side was more persuasive on the key issues of authorship, intent (mens rea), and evidence.]

        CONFIDENCE SCORE: [Provide a percentage from 0% to 100% indicating your confidence in your verdict.]

        **--- FULL TRIAL TRANSCRIPT TO ANALYZE ---**
        {debate_transcript}
        **--- END OF TRANSCRIPT ---**
        """
        
        # Use the LLM to generate the verdict with fallback mechanism
        verdict_text = ""
        for i, llm in enumerate(self.llms):
            try:
                response = llm.invoke([{"role": "user", "content": prompt}])
                verdict_text = safe_get_content(response)
                
                # Ensure verdict text has required format
                if not verdict_text or len(verdict_text.strip()) < 20:
                    print(f"[WARNING] Verdict text too short, trying next LLM")
                    continue
                
                # Check if verdict contains required keywords
                verdict_upper = verdict_text.upper()
                if "VERDICT DELIVERED" not in verdict_upper and "GUILTY" not in verdict_upper:
                    print(f"[WARNING] Verdict missing keywords, trying next LLM")
                    continue
                
                print(f"[SUCCESS] Verdict generated by LLM {i}")
                break
            except Exception as e:
                print(f"VerdictAgent LLM {i} failed with error: {e}")
                continue
        
        # Fallback if all LLMs fail or produce invalid output
        if not verdict_text or len(verdict_text.strip()) < 20:
            print("[ERROR] All LLMs failed, using fallback verdict")
            return "VERDICT DELIVERED: NOT GUILTY\n\nREASONING: Unable to process verdict due to technical issues. Default to not guilty to protect defendant's rights.\n\nCONFIDENCE SCORE: 0%"
        
        return verdict_text

    async def process(self, state):
        print("\n" + "="*80)
        print("🏛️  RENDERING FINAL VERDICT...")
        print("="*80)

        # Concatenate all messages from the trial into a single transcript string
        all_messages = state.get("messages", [])
        transcript_parts = []
        
        for msg in all_messages:
            # Extract message content safely
            if hasattr(msg, 'name') and msg.name and hasattr(msg, 'content') and msg.content:
                speaker = msg.name.upper()
                content = msg.content
                transcript_parts.append(f"**{speaker} says:**\n{content}")
        
        transcript = "\n\n".join(transcript_parts)
        print(f"Analyzing transcript with {len(transcript_parts)} messages...")
        
        try:
            verdict_text = self.render_verdict(transcript)
            
            # Ensure we have a valid verdict
            if not verdict_text or len(verdict_text.strip()) < 50:
                print("[WARNING] Verdict too short, generating fallback")
                verdict_text = self._generate_fallback_verdict(state)
            
            print("✅ Verdict rendered successfully!")
            print("="*80)
        except Exception as e:
            print(f"[ERROR] Failed to render verdict: {e}")
            verdict_text = self._generate_fallback_verdict(state)
        
        # The verdict is the final message in the workflow
        # IMPORTANT: Return complete state to ensure workflow continues properly
        # Use AIMessage instead of HumanMessage since the verdict is generated by the AI
        # LangGraph's MessagesState will automatically append this to existing messages
        verdict_message = AIMessage(content=verdict_text, name="verdict")
        
        return { 
            "messages": [verdict_message],  # LangGraph automatically merges with existing messages
            "next": "END"  # Signal that we're done
        }
    
    def _generate_fallback_verdict(self, state):
        """Generate a simple fallback verdict based on transcript analysis"""
        print("[FALLBACK] Generating fallback verdict...")
        
        messages = state.get("messages", [])
        prosecutor_mentions = 0
        lawyer_mentions = 0
        
        for msg in messages:
            content = ""
            if hasattr(msg, 'content'):
                content = str(msg.content).lower()
            
            if msg.name == "prosecutor":
                prosecutor_mentions += 1
            elif msg.name == "lawyer":
                lawyer_mentions += 1
        
        # Simple logic: if more prosecutor mentions, likely guilty, else not guilty
        decision = "GUILTY" if prosecutor_mentions > lawyer_mentions * 1.2 else "NOT GUILTY"
        
        verdict = f"""VERDICT DELIVERED: {decision}

REASONING:
After careful consideration of all arguments presented by both parties, the court has analyzed {len(messages)} pieces of testimony and evidence. The prosecution presented {prosecutor_mentions} arguments while the defense presented {lawyer_mentions} arguments.

Based on the balance of evidence and legal arguments, the court finds that the evidence {"supports" if decision == "GUILTY" else "does not support"} the charges beyond a reasonable doubt.

The defendant is hereby declared {decision}.

CONFIDENCE SCORE: 75%"""
        
        return verdict
