# in agents/verdict_agent.py

from langchain_core.messages import HumanMessage, AIMessage
from .base import safe_get_content

class VerdictAgent:
    def __init__(self, llms):
        self.llms = llms

    def render_verdict(self, debate_transcript: str):
        """Generate comprehensive verdict based on entire trial transcript"""
        prompt = f"""
You are the Presiding Judge delivering the FINAL VERDICT in a criminal trial. You have reviewed the complete trial transcript including all arguments from both prosecution and defense.

YOUR SOLE RESPONSIBILITY: Analyze the trial and deliver a definitive verdict.

ANALYSIS FRAMEWORK - Consider these factors systematically:

1. EVIDENCE EVALUATION:
   - What concrete evidence was presented by each side?
   - How credible and substantial is the evidence?
   - Were there forensic reports, witness testimonies, or documentary evidence?

2. LEGAL ARGUMENTS STRENGTH:
   - Which side presented stronger legal arguments with proper citations?
   - Were IPC sections and case precedents properly applied?
   - Did arguments have logical consistency?

3. BURDEN OF PROOF:
   - Did the prosecution prove guilt "beyond reasonable doubt"?
   - Or did the defense successfully create "reasonable doubt"?
   - In criminal law, doubt favors the defendant

4. KEY ISSUES ANALYSIS:
   - Intent (mens rea): Was criminal intent proven?
   - Act (actus reus): Was the criminal act established?
   - Causation: Was the defendant's action the direct cause?

CRITICAL RULES:
- Base your verdict ONLY on what was presented in the trial transcript
- Do NOT introduce new facts or arguments
- If both sides made strong arguments, favor the defense (reasonable doubt principle)
- Be objective and impartial

OUTPUT FORMAT (MANDATORY):

VERDICT DELIVERED: [GUILTY / NOT GUILTY]

CASE SUMMARY:
[Brief 2-3 sentence summary of what this case was about]

EVIDENCE ANALYSIS:
[Evaluate the key evidence presented by both sides. Which evidence was more compelling?]

LEGAL ARGUMENTS ASSESSMENT:
Prosecution's Arguments: [Summarize strength and weaknesses]
Defense's Arguments: [Summarize strength and weaknesses]

BURDEN OF PROOF EVALUATION:
[Did prosecution meet the "beyond reasonable doubt" standard? Or did defense create reasonable doubt?]

REASONING FOR VERDICT:
[Detailed explanation of why you reached this verdict. Reference specific arguments and evidence from the transcript. Explain which side was more persuasive and why.]

CONFIDENCE SCORE: [0-100]%
[Your confidence in this verdict based on clarity of evidence and arguments]

**--- COMPLETE TRIAL TRANSCRIPT ---**
{debate_transcript}
**--- END OF TRANSCRIPT ---**

Now, deliver your verdict following the exact format above:
"""
        
        # Use LLM with fallback mechanism
        verdict_text = ""
        for i, llm in enumerate(self.llms):
            try:
                response = llm.invoke([{"role": "user", "content": prompt}])
                verdict_text = safe_get_content(response)
                
                # Validate verdict format
                if not verdict_text or len(verdict_text.strip()) < 50:
                    print(f"[WARNING] Verdict text too short from LLM {i}, trying next")
                    continue
                
                # Check for required components
                verdict_upper = verdict_text.upper()
                has_verdict = "VERDICT DELIVERED" in verdict_upper or "GUILTY" in verdict_upper or "NOT GUILTY" in verdict_upper
                has_reasoning = "REASONING" in verdict_upper or "ANALYSIS" in verdict_upper
                
                if not has_verdict:
                    print(f"[WARNING] Verdict missing verdict statement from LLM {i}, trying next")
                    continue
                
                print(f"[SUCCESS] Verdict generated by LLM {i}")
                break
            except Exception as e:
                print(f"[ERROR] VerdictAgent LLM {i} failed: {e}")
                continue
        
        # Fallback if all LLMs fail
        if not verdict_text or len(verdict_text.strip()) < 50:
            print("[ERROR] All LLMs failed to generate valid verdict, using fallback")
            return """VERDICT DELIVERED: NOT GUILTY

REASONING: Due to technical difficulties in processing the trial transcript, and in accordance with the legal principle that doubt must favor the defendant, this court declares the defendant NOT GUILTY. The prosecution bears the burden of proving guilt beyond reasonable doubt, and in the absence of a properly rendered analysis, that burden cannot be considered met.

CONFIDENCE SCORE: 0%

This is a default verdict issued due to system limitations and does not reflect the actual merits of the case."""
        
        return verdict_text

    async def process(self, state):
        print("\n" + "="*80)
        print("🏛️  RENDERING FINAL VERDICT...")
        print("="*80)

        # Concatenate all messages from the trial into a single transcript string
        all_messages = state.get("messages", [])
        transcript_parts = []
        
        for msg in all_messages:
            # Extract message content safely
            msg_name = getattr(msg, "name", "") or (msg.get("name", "") if isinstance(msg, dict) else "")
            content = getattr(msg, "content", "") or (msg.get("content", "") if isinstance(msg, dict) else "")
            if msg_name and content:
                speaker = str(msg_name).upper()
                transcript_parts.append(f"**{speaker} says:**\n{content}")
        
        transcript = "\n\n".join(transcript_parts)
        print(f"Analyzing transcript with {len(transcript_parts)} messages...")
        
        try:
            verdict_text = self.render_verdict(transcript)
            
            # Ensure we have a valid verdict
            if not verdict_text or len(verdict_text.strip()) < 50:
                print("[WARNING] Verdict too short, generating fallback")
                verdict_text = self._generate_fallback_verdict(state)
            
            print("✅ Verdict rendered successfully!")
            print("="*80)
        except Exception as e:
            print(f"[ERROR] Failed to render verdict: {e}")
            verdict_text = self._generate_fallback_verdict(state)
        
        # The verdict is the final message in the workflow
        # IMPORTANT: Return complete state to ensure workflow continues properly
        # Use AIMessage instead of HumanMessage since the verdict is generated by the AI
        # LangGraph's MessagesState will automatically append this to existing messages
        verdict_message = AIMessage(content=verdict_text, name="verdict")
        
        return { 
            "messages": [verdict_message],  # LangGraph automatically merges with existing messages
            "next": "END"  # Signal that we're done
        }
    
    def _generate_fallback_verdict(self, state):
        """Generate a structured fallback verdict based on transcript analysis"""
        print("[FALLBACK] Generating structured fallback verdict...")
        
        messages = state.get("messages", [])
        
        # Analyze conversation for key indicators
        prosecutor_args = []
        lawyer_args = []
        judge_comments = []
        
        for msg in messages:
            content = ""
            name = ""
            if hasattr(msg, 'content'):
                content = str(msg.content).lower()
            if hasattr(msg, 'name'):
                name = msg.name
            
            if name == "prosecutor" and len(content) > 50:
                prosecutor_args.append(content)
            elif name == "lawyer" and len(content) > 50:
                lawyer_args.append(content)
            elif name == "judge" and len(content) > 50:
                judge_comments.append(content)
        
        # Count key legal terms and strength indicators
        prosecutor_strength = sum([
            content.count('evidence') + content.count('proof') + 
            content.count('ipc') + content.count('section')
            for content in prosecutor_args
        ])
        
        lawyer_strength = sum([
            content.count('defense') + content.count('reasonable doubt') + 
            content.count('insufficient') + content.count('not proven')
            for content in lawyer_args
        ])
        
        # Determine verdict based on analysis
        # In criminal law, tie or close calls favor defense (reasonable doubt)
        if lawyer_strength > prosecutor_strength * 0.8:  # Defense needs less to create doubt
            decision = "NOT GUILTY"
            reasoning = f"""After analyzing {len(prosecutor_args)} prosecution arguments and {len(lawyer_args)} defense arguments, the court finds that the prosecution has not met the burden of proving guilt beyond a reasonable doubt.

The defense successfully raised sufficient questions regarding the evidence and legal interpretation. In criminal proceedings, any reasonable doubt must favor the defendant.

Key factors:
- Defense presented {lawyer_strength} substantive legal points
- Prosecution presented {prosecutor_strength} substantive legal points
- The evidence presented was insufficient to overcome reasonable doubt"""
        else:
            decision = "GUILTY"
            reasoning = f"""After analyzing {len(prosecutor_args)} prosecution arguments and {len(lawyer_args)} defense arguments, the court finds that the prosecution has successfully proven the case beyond a reasonable doubt.

The evidence and legal arguments presented by the prosecution were more compelling and substantial than those presented by the defense.

Key factors:
- Prosecution presented {prosecutor_strength} substantive legal points with evidence
- Defense presented {lawyer_strength} counterarguments
- The prosecution's evidence was sufficient to establish guilt"""
        
        confidence = min(75, max(40, abs(prosecutor_strength - lawyer_strength) * 5))
        
        verdict = f"""VERDICT DELIVERED: {decision}

CASE SUMMARY:
This case involved criminal charges where the prosecution and defense presented their respective arguments over the course of {len(messages)} courtroom exchanges.

EVIDENCE ANALYSIS:
The trial featured {len(prosecutor_args)} prosecutorial arguments and {len(lawyer_args)} defense arguments. The court evaluated the strength, relevance, and legal grounding of all submitted evidence and testimonies.

LEGAL ARGUMENTS ASSESSMENT:
Prosecution's Arguments: Presented {len(prosecutor_args)} arguments with {prosecutor_strength} key legal points and evidence citations.
Defense's Arguments: Presented {len(lawyer_args)} arguments with {lawyer_strength} key legal points and reasonable doubt assertions.

BURDEN OF PROOF EVALUATION:
{reasoning}

CONFIDENCE SCORE: {confidence}%

[NOTE: This is a fallback verdict generated due to system limitations. Manual review recommended.]"""
        
        return verdict
